# rename this file to config.yaml before start

# qqbot account, not needed anymore for qrcode authentication
account:  3274747072
password: ""

# server to view verification code, not required for mac
port: 12890
host: localhost

# message handling, ignore offline message 20 min ago
# offline_msg_keeptime: 1200

# plugin list
plugins:
    - help
    - debug
    - apiserver

# apiserver plugin configration
api_port:  12990
api_token: ''
