// Generated by CoffeeScript 1.10.0
(function() {
    var api, auth, auth_opts, config, defaults, int, jsons, log, pass, qq, test_api, qqbot;

    int = function(v) {
        return parseInt(v);
    };

    log = console.log;

    auth = require("../src/qqauth");

    qqbot = require("../src/qqbot");

    api = require("../src/qqapi");

    defaults = require('../src/defaults');

    config = require('../config');

    qq = config.account;

    pass = config.password;

    jsons = JSON.stringify;

    api.cookies(defaults.data('qq-cookie'));

    auth_opts = defaults.data('qq-auth');


    /*
    auth_opts ={
        psessionid
        clientid
        ptwebqq
        uin
        vfwebqq
    }
     */

    test_api = function() {
        console.log(auth_opts);
        return api.send_msg_2buddy(1844447029, "庆贺一郎 " + (new Date()), auth_opts, function(ret, e) {
            return log("group send ret:", ret);
        });

    };

    test_api();

}).call(this);
